# Generated by Django 2.2.7 on 2020-01-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0002_auto_20170310_0642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageseries',
            options={'verbose_name_plural': 'Image Series'},
        ),
        migrations.AddField(
            model_name='imageseries',
            name='image_folder',
            field=models.FileField(default='jZHC2YX', upload_to='image_dumps'),
            preserve_default=False,
        ),
    ]
