# Generated by Django 2.2.7 on 2020-01-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0003_auto_20200112_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageseries',
            name='image_folder',
            field=models.FileField(upload_to='image_dumps/'),
        ),
    ]
