# Generated by Django 2.2.7 on 2020-01-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slicer', '0004_auto_20200113_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageseries',
            name='image_folder',
            field=models.CharField(max_length=16),
        ),
    ]
